import {test} from 'node:test';import assert from 'node:assert/strict';import {createHmac,randomUUID} from 'node:crypto';
process.env.NODE_ENV='test';process.env.DEMO_JWT_SECRET='hosted-test-signing-key-at-least-32-characters';
const {runPersistedRequest,StorageConflict}=await import('../frontend/server/session-engine.mjs');
function token(sub){const header=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url');const payload=Buffer.from(JSON.stringify({sub,role:'authenticated',exp:Math.floor(Date.now()/1000)+3600})).toString('base64url');return `${header}.${payload}.${createHmac('sha256',process.env.DEMO_JWT_SECRET).update(`${header}.${payload}`).digest('base64url')}`}
class Store {rows=new Map();writes=0;async read(key){const row=this.rows.get(key);return row?{etag:row.etag,data:JSON.parse(row.body)}:null}async write(key,body,etag){const current=this.rows.get(key);if(current?.etag!==etag)throw new StorageConflict();this.writes++;this.rows.set(key,{body,etag:String(this.writes)})}}
function request(store,userId,path,body,key){return runPersistedRequest({userId,event:{httpMethod:body===undefined?'GET':'POST',path,headers:{'content-type':'application/json',authorization:`Bearer ${token(userId)}`,...(key?{'idempotency-key':key}:{})},body:body===undefined?undefined:JSON.stringify(body),requestContext:{identity:{sourceIp:'127.0.0.1'}},isBase64Encoded:false}},store).then(r=>({status:r.statusCode,...JSON.parse(r.body)}))}
const kyc={fullName:'Fictional Sender',dateOfBirth:'1993-04-12',idType:'NATIONAL_ID',idNumber:'DEMO123456',country:'ARE'};
const quote={sourceCurrency:'AED',targetCurrency:'INR',sendAmountMinor:100000};
test('hosted snapshots persist the complete original transfer flow across requests',async()=>{const store=new Store(),user=randomUUID();assert.equal((await request(store,user,'/kyc/submit',kyc)).data.status,'APPROVED');const q=await request(store,user,'/quotes',quote);const payload={quoteId:q.data.id,recipientDetails:{name:'Fictional Recipient',upi_id:'fictional@demobank',country:'IND'}},key=randomUUID();const t=await request(store,user,'/transfers',payload,key);assert.equal(t.data.status,'AWAITING_FUNDS');assert.equal((await request(store,user,'/transfers',payload,key)).data.id,t.data.id);assert.equal((await request(store,user,`/transfers/${t.data.id}/deposit`,{})).data.status,'COMPLETED');const detail=await request(store,user,`/transfers/${t.data.id}`);assert.ok(detail.data.events.length>=7);const before=store.writes;assert.equal((await request(store,user,'/transfers')).data.length,1);assert.equal(store.writes,before,'reads do not rewrite storage');assert.equal((await request(store,randomUUID(),' /transfers'.trim())).data.length,0)});
test('concurrent snapshot writes retry instead of losing quotes',async()=>{const store=new Store(),user=randomUUID();const results=await Promise.all([request(store,user,'/quotes',quote),request(store,user,'/quotes',quote)]);assert.ok(results.every(r=>r.status===201));const list=await request(store,user,'/quotes');assert.equal(list.data.length,2);assert.notEqual(list.data[0].id,list.data[1].id)});
test('concurrent users cannot read each other’s state',async()=>{const store=new Store(),a=randomUUID(),b=randomUUID();await Promise.all([request(store,a,'/kyc/submit',kyc),request(store,b,'/kyc/submit',{...kyc,idNumber:'DEMO0000'})]);assert.equal((await request(store,a,'/kyc/status')).data.status,'APPROVED');assert.equal((await request(store,b,'/kyc/status')).data.status,'REJECTED')});
test('a failed persistent write never reports a successful mutation',async()=>{const store=new Store();store.write=async()=>{throw new Error('Storage unavailable')};await assert.rejects(()=>request(store,randomUUID(),'/quotes',quote),/Storage unavailable/)});
