import assert from 'node:assert/strict';
const base=process.env.TEST_ORIGIN||'http://127.0.0.1:3100';
const titles=new Set(),descriptions=new Set();
for(const path of ['/','/login','/dashboard','/privacy','/terms']){const r=await fetch(base+path);assert.equal(r.status,200);const html=await r.text();const title=html.match(/<title>([^<]+)<\/title>/)?.[1];const description=html.match(/<meta name="description" content="([^"]+)"/i)?.[1];assert.ok(title,`${path} title`);assert.ok(description,`${path} description`);titles.add(title);descriptions.add(description);assert.ok(!html.includes('<main class="not-found'),`${path} must not render the error page`);assert.ok(html.includes('rel="icon"'));if(path==='/'){assert.equal((html.match(/aria-controls="answer-/g)||[]).length,5);assert.ok(html.includes('One transfer.'));assert.ok(!html.includes('<script src="https://www.googletagmanager.com'));}if(['/login','/privacy','/terms'].includes(path))assert.ok(html.includes('aria-label="Breadcrumb"'));if(path==='/login'||path==='/dashboard')assert.match(html,/<meta name="robots" content="[^"]*noindex/)}
assert.equal(titles.size,5);assert.equal(descriptions.size,5);
const missing=await fetch(base+'/this-route-does-not-exist');assert.equal(missing.status,404);const missingHtml=await missing.text();assert.ok(missingHtml.includes('This route doesn'));assert.match(missingHtml,/<meta name="robots" content="[^"]*noindex/);
const robots=await fetch(base+'/robots.txt');assert.equal(robots.status,200);const text=await robots.text();for(const path of ['/api/','/dashboard','/login'])assert.ok(text.includes(`Disallow: ${path}`));
const sitemap=await(await fetch(base+'/sitemap.xml')).text();assert.ok(sitemap.includes('/privacy'));assert.ok(!sitemap.includes('/dashboard'));
for(const path of ['/icon.svg','/favicon.ico','/apple-icon.png','/opengraph-image']){const r=await fetch(base+path);assert.equal(r.status,200,path);assert.match(r.headers.get('content-type'),/image\//);assert.ok((await r.arrayBuffer()).byteLength>100)}
console.log('PASS: unique titles and descriptions, five FAQs, breadcrumbs, true 404 response, noindex, robots, sitemap, custom icons, social preview, inactive analytics.');
