import type { Metadata } from "next";
import Link from "next/link";
import { TextType } from "@/UI/text-type";
import { DarkGradientBg } from "@/components/ui/elegant-dark-pattern";
import {
  ArrowRight,
  FileText,
  Mail,
  TrendingUp,
  Zap,
  Shield,
  BarChart3,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Trader Invoice Mailer — Professional invoice tracking for traders",
  description:
    "Track invoices, manage trades, and send AI-powered payment reminder emails in seconds. Built for traders.",
};

const features = [
  {
    icon: FileText,
    title: "Smart invoice tracking",
    body: "Organise open, in-progress and closed invoices with full audit trails.",
  },
  {
    icon: Mail,
    title: "AI-drafted emails",
    body: "One click generates a polished, professional payment reminder — no manual writing.",
  },
  {
    icon: TrendingUp,
    title: "Per-track insights",
    body: "Group invoices by trading segment (Nifty 50, Bank Nifty…) and see the big picture.",
  },
  {
    icon: Zap,
    title: "Instant generation",
    body: "Sub-second template fallback means you always get an email, even offline.",
  },
  {
    icon: Shield,
    title: "Secure by design",
    body: "Row-level security via Supabase — your data is never shared across accounts.",
  },
  {
    icon: BarChart3,
    title: "Indian currency native",
    body: "Amounts displayed as ₹ in Indian format. Stored as paise internally — no rounding errors.",
  },
];

export default function LandingPage() {
  return (
    <DarkGradientBg>
    <main className="relative overflow-hidden">
      {/* Hero */}
      <section className="relative flex min-h-screen flex-col items-center justify-center px-4 text-center">
        <div className="relative z-10 max-w-4xl">
          {/* Badge */}
          <span className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan-100/20 bg-white/[0.06] px-4 py-1.5 text-xs font-medium tracking-wide text-cyan-100 backdrop-blur-sm">
            <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-cyan-300" />
            Built for Indian traders
          </span>

          <h1 className="mt-4 text-4xl font-extrabold tracking-tight text-white sm:text-6xl lg:text-7xl">
            Invoice tracking
            <br />
            <span className="gradient-text">
              <TextType
                text={["powered by AI.", "done in seconds.", "built for traders."]}
                typingSpeed={45}
                pauseDuration={2200}
                deletingSpeed={25}
              />
            </span>
          </h1>

          <p className="mx-auto mt-6 max-w-2xl text-lg text-cyan-50/80">
            Manage your trades, track invoices by status, and send polished
            payment reminder emails — generated by AI in one click.
          </p>

          <div className="mt-10 flex flex-wrap items-center justify-center gap-4">
            <Link
              href="/signup"
              id="cta-signup"
              className="group inline-flex items-center gap-2 rounded-xl bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground shadow-lg shadow-cyan-950/40 transition-all hover:bg-cyan-300 hover:shadow-cyan-700/30 focus:outline-none focus:ring-2 focus:ring-cyan-200"
            >
              Get started free
              <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
            </Link>
            <Link
              href="/login"
              id="cta-login"
              className="inline-flex items-center gap-2 rounded-xl border border-cyan-100/20 bg-white/[0.06] px-6 py-3 text-sm font-semibold text-white backdrop-blur-sm transition-all hover:bg-cyan-100/10 focus:outline-none focus:ring-2 focus:ring-cyan-100/30"
            >
              Sign in
            </Link>
          </div>
        </div>

        {/* Scroll indicator */}
        <div className="absolute bottom-8 left-1/2 z-10 -translate-x-1/2 animate-bounce">
          <div className="h-8 w-5 rounded-full border-2 border-white/30 flex items-start justify-center pt-1.5">
            <div className="h-1.5 w-1 rounded-full bg-white/60" />
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="border-y border-cyan-100/[0.06] bg-black/20 px-4 py-24 backdrop-blur-sm">
        <div className="mx-auto max-w-6xl">
          <div className="text-center">
            <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
              Everything you need to{" "}
              <span className="gradient-text">get paid faster</span>
            </h2>
            <p className="mt-4 text-base text-slate-400">
              A complete toolkit for traders who mean business.
            </p>
          </div>

          <div className="mt-16 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((f) => (
              <div
                key={f.title}
                className="group rounded-2xl border border-cyan-100/[0.08] bg-slate-950/55 p-6 backdrop-blur-xl transition-all hover:border-cyan-100/20 hover:bg-slate-900/70"
              >
                <div className="mb-4 inline-flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-300/10 text-cyan-200">
                  <f.icon className="h-5 w-5" strokeWidth={1.5} />
                </div>
                <h3 className="text-base font-semibold text-white">{f.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-slate-400">{f.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA section */}
      <section className="relative overflow-hidden border-t border-cyan-100/10 bg-cyan-950/30 px-4 py-24 text-center backdrop-blur-sm">
        <div className="relative z-10 mx-auto max-w-2xl">
          <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
            Ready to streamline your invoicing?
          </h2>
          <p className="mt-4 text-base text-cyan-100/70">
            Join traders who trust Invoice Mailer to keep payments on track.
          </p>
          <Link
            href="/signup"
            className="mt-8 inline-flex items-center gap-2 rounded-xl bg-primary px-8 py-3 text-sm font-semibold text-primary-foreground shadow-lg shadow-cyan-950/30 transition-all hover:bg-cyan-300 focus:outline-none focus:ring-2 focus:ring-cyan-200"
          >
            Create your free account
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
        {/* Decorative blobs */}
        <div className="pointer-events-none absolute -left-24 -top-24 h-96 w-96 rounded-full bg-cyan-800/20 blur-3xl" />
        <div className="pointer-events-none absolute -bottom-24 -right-24 h-96 w-96 rounded-full bg-blue-800/20 blur-3xl" />
      </section>

      {/* Footer */}
      <footer className="border-t border-cyan-100/[0.06] bg-black/35 px-4 py-8 text-center text-xs text-slate-500">
        © {new Date().getFullYear()} Trader Invoice Mailer. All rights reserved.
      </footer>
    </main>
    </DarkGradientBg>
  );
}
