'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight} from 'lucide-react';
import CurrencySelectors from './currency-selectors';
import {currency,money,toMinor} from '@/lib/remittance/currency';
type Estimate={feeMinor:number;exchangeRate:number;receiveAmountMinor:number;rateDate:string};
export default function CurrencyEstimate({source,target,amount,onAmount,onChange}:{source:string;target:string;amount:string;onAmount:(value:string)=>void;onChange:(source:string,target:string)=>void}){
 const [retry,setRetry]=useState(0);const [result,setResult]=useState<{key:string;data?:Estimate;error?:string}|null>(null);const minor=toMinor(amount,source),key=`${source}:${target}:${minor}`;
 useEffect(()=>{if(minor===null)return;const controller=new AbortController();const timer=setTimeout(async()=>{try{const r=await fetch(`/api/backend/quotes/estimate?source=${source}&target=${target}&amount=${minor}`,{signal:controller.signal});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'Rates unavailable. Please retry.');setResult({key,data:j.data})}catch(e){if(!controller.signal.aborted)setResult({key,error:(e as Error).message})}},300);return()=>{clearTimeout(timer);controller.abort()}},[key,minor,source,target,retry]);
 const data=result?.key===key?result.data:undefined,error=minor===null?`Enter a positive amount with up to ${currency(source).decimals} decimal places, no more than 1,000,000 ${source}.`:result?.key===key?result.error:undefined;
 return <div className="quote-card"><div className="quote-heading"><span>Your money, before it moves.</span><ArrowUpRight size={18}/></div><CurrencySelectors source={source} target={target} onChange={onChange}/><label htmlFor="send-amount">Sending amount</label><div className="currency-input"><input id="send-amount" type="number" min={10**-currency(source).decimals} max="1000000" step={10**-currency(source).decimals} value={amount} onChange={e=>onAmount(e.target.value)} aria-describedby="estimate-note"/><span>{source}</span></div><div className="quote-breakdown"><span>Transfer fee</span><b>{data?money(data.feeMinor,source):'Pending'}</b><span>Daily reference rate</span><b>{data?`1 ${source} = ${data.exchangeRate.toLocaleString('en-GB',{maximumFractionDigits:6})} ${target}`:error?'Unavailable':'Loading rate...'}</b></div><div className="receive-box" aria-live="polite"><span>They receive</span><div><strong>{data?money(data.receiveAmountMinor,target):error?'Unavailable':'Calculating...'}</strong></div></div><a href={`/dashboard?source=${source}&target=${target}&amount=${encodeURIComponent(amount)}`} className="button dark full">Get a demo quote<ArrowRight size={17}/></a><p id="estimate-note" className="fine" role={error?'status':undefined}>{error|| (data?`Reference date: ${data.rateDate}. Your final quote is held for 60 seconds.`:'Fetching the latest available daily reference rate.')}</p>{error&&minor!==null&&<button type="button" className="text-button" onClick={()=>{setResult(null);setRetry(n=>n+1)}}>Retry reference rate</button>}<a className="rate-source" href="https://frankfurter.dev/" target="_blank" rel="noreferrer">Reference rates by Frankfurter</a></div>
}
