'use client';
import {useRef,useState} from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {ArrowRight,ArrowUpRight,ArrowDown,Check,ShieldCheck,Route,Wallet,Plus,Minus,LockKeyhole} from 'lucide-react';
import gsap from 'gsap';import {ScrollTrigger} from 'gsap/ScrollTrigger';import {useGSAP} from '@gsap/react';
import {Header,Footer} from './chrome';
import TransferStory from './transfer-story';
import {faqs} from '@/lib/remittance/site';
const Globe=dynamic(()=>import('./globe'),{ssr:false,loading:()=> <div className="globe-stage"><div className="globe-fallback"/></div>});
gsap.registerPlugin(ScrollTrigger,useGSAP);
const steps=[{title:'Start with a clear quote.',body:'Choose how much to send in AED. See the exchange rate, the fee, and the amount in INR before you commit.',icon:Wallet},{title:'Verified before it moves.',body:'Identity verification and transaction screening happen before value enters the transfer journey.',icon:ShieldCheck},{title:'Follow every step home.',body:'From simulated deposit to token escrow and INR payout, each state change appears in your transfer timeline.',icon:Route}];
export default function Landing(){const root=useRef<HTMLDivElement>(null);const [amount,setAmount]=useState('1000');const [open,setOpen]=useState(0);const n=Number(amount);const minor=Math.round(n*100);const fee=500+Math.round(minor*.005);const valid=Number.isFinite(n)&&minor>fee&&n<=1000000;const receive=valid?Math.round((minor-fee)*22.7)/100:0;
 useGSAP(()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{gsap.from('.hero-copy > *',{y:22,opacity:0,stagger:.1,duration:.85,ease:'power3.out'});gsap.to('.scroll-progress',{scaleX:1,ease:'none',scrollTrigger:{trigger:root.current,start:'top top',end:'bottom bottom',scrub:.2}});gsap.fromTo('.closing h2',{backgroundSize:'0% 100%,100% 100%'},{backgroundSize:'100% 100%,100% 100%',ease:'none',scrollTrigger:{trigger:'.closing',start:'top 85%',end:'top 30%',scrub:true}});gsap.fromTo('.hero-visual',{y:0},{y:-28,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:true}});gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.from(el,{y:30,opacity:0,duration:.75,scrollTrigger:{trigger:el,start:'top 92%',once:true}}));});mm.add('(min-width: 960px) and (prefers-reduced-motion: no-preference)',()=>{ScrollTrigger.create({trigger:'.journey',start:'top 120px',end:'bottom 75%',pin:'.journey-intro',pinSpacing:false});gsap.utils.toArray<HTMLElement>('.journey-card').forEach((el,i)=>gsap.to(el,{scale:1-i*.025,scrollTrigger:{trigger:el,start:'top 45%',end:'bottom top',scrub:true}}));});return()=>mm.revert();},{scope:root});
 return <div ref={root}><div className="scroll-progress" aria-hidden="true"/><Header/><main id="main" className="landing"><section className="hero wrap"><div className="hero-copy"><p className="eyebrow"><span className="line"/> FROM THE UAE. FOR HOME.</p><h1>Send dirhams.<br/><span>They receive rupees.</span></h1><p className="hero-description">Send dirhams. Receive rupees. Follow every step.<br/>A clearer way to move money from the UAE to India.</p><div className="hero-actions"><a href="/dashboard" className="button green">Try a transfer <ArrowUpRight size={18}/></a><a href="#how-it-works" className="text-button">See how it works <ArrowDown size={16}/></a></div></div><div className="hero-visual"><Globe/><div className="quote-card"><div className="quote-heading"><span>Your money, before it moves.</span><ArrowUpRight size={18}/></div><label htmlFor="send-amount">You send</label><div className="currency-input"><input id="send-amount" type="number" min="6" max="1000000" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} aria-describedby="estimate-note"/><span><span className="flag uae"/>AED</span></div><div className="quote-breakdown"><span>Transfer fee</span><b>{valid?(fee/100).toFixed(2):'0.00'} AED</b><span>Illustrative exchange rate</span><b>1 AED = 22.70 INR</b></div><div className="receive-box"><span>They receive</span><div><strong>{receive.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}</strong><span><span className="flag indian"/>INR</span></div></div><a href={valid?`/dashboard?amount=${encodeURIComponent(amount)}`:'/dashboard'} className="button dark full">Get a demo quote <ArrowRight size={17}/></a><p id="estimate-note" className="fine">{valid?'Illustrative estimate. Your final demo rate is quoted in the app.':'Enter an amount above the fee, up to AED 1,000,000.'}</p></div></div><div className="hero-bottom"><span><LockKeyhole size={14}/> Clear fees. Traceable transfers.</span><span>Built on blockchain. Designed around people.</span><a href="#why-corridor" aria-label="Explore Corridor"><ArrowDown size={19}/></a></div></section>
 <section id="why-corridor" className="features-section"><div className="wrap"><div className="section-heading reveal"><p className="eyebrow">LESS GUESSWORK. MORE CLARITY.</p><h2>Cross borders.<br/>Keep your peace of mind.</h2><p>A transfer should be easy to understand.<br/>From the first quote to the final confirmation.</p></div><div className="feature-grid"><article className="feature reveal"><div className="feature-graphic fee-graphic"><span>AED</span><div className="receipt"><span>Transfer amount <b>1,000.00</b></span><span>Transfer fee <b>10.00</b></span><hr/><span>Ready to convert <b>990.00</b></span></div></div><h3>No fee hide-and-seek.</h3><p>Your quote separates the fee, conversion rate, and recipient amount. Everything in view before you confirm.</p></article><article className="feature reveal"><div className="feature-graphic path-graphic"><span className="path-node"><Wallet/></span><i/><span className="path-node central"><ShieldCheck/></span><i/><span className="path-node"><Check/></span><small>DEPOSIT → ESCROW → PAYOUT</small></div><h3>A journey you can follow.</h3><p>See when funds arrive, when escrow locks, and when payout completes. A timeline replaces the uncertainty.</p></article><article className="feature reveal"><div className="feature-graphic coin-graphic"><div className="coin"><LockKeyhole size={44}/></div><span className="coin-shadow"/></div><h3>Checks built into the flow.</h3><p>Identity checks and transaction screening come first. Smart contract escrow records the movement of test tokens.</p></article></div></div></section>
 <section id="how-it-works" className="journey wrap"><div className="journey-intro"><p className="eyebrow">HERE TO THERE, EXPLAINED.</p><h2>Different countries.<br/>One clear journey.</h2><p>You send in a currency you know.<br/>They receive in the one they use.</p><a href="/dashboard" className="text-button">Explore the demo <ArrowUpRight size={18}/></a><div className="route-stamp"><span>AE</span><div/><ArrowRight/><div/><span>IN</span></div></div><div className="journey-panels">{steps.map((s,i)=><article className="journey-card" key={s.title}><div className="step-top"><s.icon size={25} strokeWidth={1.5}/><span>0{i+1}</span></div><h3>{s.title}</h3><p>{s.body}</p><div className="step-detail">{i===0?'AED → INR · 60-second quote':i===1?'Identity → Screening → Escrow':'Deposit → On-chain record → Payout'}</div></article>)}</div></section>
 <TransferStory/><section id="faq" className="honesty wrap reveal"><div><p className="eyebrow">GOOD QUESTIONS. CLEAR ANSWERS.</p><h2>Before you<br/>make a move.</h2></div><div className="accordion">{faqs.map((f,i)=><div className="faq" key={f.q}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i} aria-controls={`answer-${i}`}>{f.q}{open===i?<Minus size={17}/>:<Plus size={17}/>}</button><div id={`answer-${i}`} hidden={open!==i}><p>{f.a}</p></div></div>)}</div></section>
 <section className="closing"><div className="wrap reveal"><p className="eyebrow">A LITTLE LESS DISTANCE.</p><h2>For the life you build.<br/>And the people back home.</h2><a href="/dashboard" className="button light">Make your first demo transfer <ArrowUpRight size={19}/></a><p>UAE to India. Start with a quote.</p></div><span className="closing-orbit"/></section></main><Footer/></div>
}
