'use client';
import {currency} from '@/lib/remittance/currency';
import {useRef,useState} from 'react';import dynamic from 'next/dynamic';import {ArrowDown,ArrowUpRight,Wallet,LockKeyhole,Landmark} from 'lucide-react';import Link from 'next/link';import gsap from 'gsap';import {ScrollTrigger} from 'gsap/ScrollTrigger';import {useGSAP} from '@gsap/react';
const Object3D=dynamic(()=>import('./transfer-object'),{ssr:false,loading:()=> <div className="transfer-object"/>});
gsap.registerPlugin(ScrollTrigger,useGSAP);
export default function TransferStory({source='AED',target='INR'}:{source?:string;target?:string}){const from=currency(source),to=currency(target);const chapters=[{label:'You send',currency:source,title:`It starts with your ${from.plural}.`,body:`See the fee and the ${target} amount upfront. Once you confirm, a simulated deposit starts the journey.`,icon:Wallet},{label:'Value moves',currency:'RMTS',title:'A record for every move.',body:'Test tokens represent the value in transit. Your transfer records each step through screening and the simulated chain service.',icon:LockKeyhole},{label:'They receive',currency:target,title:`${to.name}, at the other end.`,body:'The simulated bank payout completes the journey. Follow the status and the final reference in your transfer timeline.',icon:Landmark}];const root=useRef<HTMLElement>(null);const trigger=useRef<ScrollTrigger|null>(null);const [phase,setPhase]=useState(0);const active=Math.min(2,Math.round(phase));const chapter=chapters[active];
 useGSAP(()=>{const mm=gsap.matchMedia();mm.add('(min-width: 960px) and (prefers-reduced-motion: no-preference)',()=>{trigger.current=ScrollTrigger.create({trigger:root.current,start:'top top',end:'+=1500',pin:true,anticipatePin:1,onUpdate:self=>setPhase(Math.round(self.progress*200)/100)});return()=>{trigger.current=null}});return()=>mm.revert()},{scope:root});
 function choose(i:number){const t=trigger.current;if(t){window.scrollTo({top:t.start+(t.end-t.start)*(i/2),behavior:'smooth'})}else setPhase(i)}
 return <section ref={root} className="transfer-story" aria-label="Explore the transfer journey"><div className="wrap story-grid"><div className="story-copy"><p className="eyebrow">FOLLOW THE VALUE</p><h2>One transfer.<br/>A visible path.</h2><p className="story-intro">A closer look at what happens<br/>between here and home.</p><div className="story-chapter" aria-live="polite"><chapter.icon size={25} strokeWidth={1.4}/><h3>{chapter.title}</h3><p>{chapter.body}</p></div><a href={`/dashboard?source=${source}&target=${target}`} className="text-button">Try the whole journey<ArrowUpRight size={17}/></a></div><div className="story-scene"><div className="scene-coordinate">{from.city} → {to.city} <span>{source} → {target}</span></div><Object3D phase={phase} source={source} destination={target}/><div className="story-tabs" role="tablist" aria-label="Transfer stage">{chapters.map((c,i)=><button key={c.currency} id={`story-tab-${i}`} role="tab" aria-selected={active===i} aria-controls="story-stage" tabIndex={active===i?0:-1} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=(i+(e.key==='ArrowRight'?1:2))%3;choose(next);document.getElementById(`story-tab-${next}`)?.focus()}}} onClick={()=>choose(i)}><span>{c.label}</span><strong>{c.currency}</strong><i style={{transform:`scaleX(${active===i?1:0})`}}/></button>)}</div><div id="story-stage" role="tabpanel" aria-labelledby={`story-tab-${active}`} className="scene-note"><span>Illustrative model · simulated value</span><span><ArrowDown size={13}/>Scroll to follow</span></div></div></div></section>
}
